# Generated by Django 3.0.9 on 2020-08-14 03:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_vocab_usage'),
    ]

    operations = [
        migrations.AddField(
            model_name='vocab',
            name='definition',
            field=models.CharField(default='undefined', max_length=2000, verbose_name='Definition'),
        ),
    ]
