# Generated by Django 3.0.9 on 2020-08-14 17:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_vocab_definition'),
    ]

    operations = [
        migrations.AddField(
            model_name='vocab',
            name='book',
            field=models.CharField(default='undefined', max_length=255, verbose_name='Word'),
        ),
    ]
