# Generated by Django 3.0.9 on 2020-08-14 17:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_vocab_book'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vocab',
            name='book',
            field=models.CharField(default='undefined', max_length=255, verbose_name='Book'),
        ),
    ]
