# Generated by Django 3.0.9 on 2020-08-23 04:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_auto_20200814_1056'),
    ]

    operations = [
        migrations.AddField(
            model_name='vocab',
            name='cull_status',
            field=models.BooleanField(default=False),
        ),
    ]
