# Generated by Django 3.0.9 on 2020-08-23 04:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_vocab_cull_status'),
    ]

    operations = [
        migrations.RenameField(
            model_name='vocab',
            old_name='cull_status',
            new_name='prevent_cull',
        ),
    ]
